# Site settings

title: wangxian                     # Title of your site
email: 18170875446@126.com          # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog/"                           # the subpath of your site, e.g. /blog/
url: "http://wangxian0718.github.io"        # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     july_mao                        # Replace this with your Twitter username
github_username:      wangxian0718                    # Replace this with your GitHub username
google_mail_username: wangxian19940718@gmail.com      # Replace this with your Google+ username
facebook_username:    wangxian1994                    # Replace this with your Facebook username

# Build settings
markdown: kramdown
